name: React Test Workflow

on: 
  push: 
    branches:
      - 'main'
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from git
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Run tests
        run: npm test
