apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-server-iis-ltsc2019
  namespace: default
spec:
  selector:
    matchLabels:
      app: windows-server-iis-ltsc2019
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: windows-server-iis-ltsc2019
        tier: backend
        track: stable
    spec:
      containers:
      - name: windows-server-iis-ltsc2019
        image: marciogmorales/iislogmonitor:latest
        command:
        - powershell.exe
        - -command
        - "Add-WindowsFeature Web-Server; Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe' -OutFile 'C:\\ServiceMonitor.exe'; echo '<html><body><br/><br/><H1>Argo CD - GitOps - Test - Dec 7, 2022 - 9:56pm!!!<H1></body><html>' > C:\\inetpub\\wwwroot\\iisstart.htm; C:\\ServiceMonitor.exe 'w3svc'; "
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
         - key: "os"
           operator: "Equal"
           value: "windows"
           effect: "NoSchedule"
--- 
apiVersion: v1
kind: Service
metadata:
  name: windows-server-iis-ltsc2019-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: windows-server-iis-ltsc2019
    tier: backend
    track: stable
  sessionAffinity: None
  type: LoadBalancer
  