name: JDeployment

on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DN_NAME: gha-demo
          
jobs:
  test:
    environment: DEV
    env: # GITHUB ENV
      MONGODB_CLUSTER_ADDRESS: ${{ vars.DEV_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.DEV_USER }}
      MONGODB_PASSWORD: ${{ secrets.DEV_PASSWORD }}
    # env: REPO INFO
    #   MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }}
    #   MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
    #   MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api_node
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Cache dependecies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}"
          echo "MONGODB_CLUSTER_ADDRESS" ${{ vars.MONGODB_CLUSTER_ADDRESS }}