name: Job Artifacts

on:
   push:
       branches:
        - main
    
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependecies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
