name: Job Artifacts

on: workflow_dispatch
    
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test code
        run: npm run test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-files
        - name: Deploy
          run: echo "Deploying..."