name: Matrix Demo
on: push
jobs:
  build:
    defaults:
      run:
        working-directory: ./second-action-react
    strategy:
      matrix:
        node-version: [16, 20]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build