name: Matrix Demo
on: workflow_dispatch
jobs:
  build:
    continue-on-error: true
    defaults:
      run:
        working-directory: ./second-action-react
    strategy:
      matrix:
        node-version: [14, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 14
            operating-system: windows-latest
       
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build