name: React Workflow

on: 
  push: 
    branches:
      - 'main'
  workflow_dispatch
    
jobs:
  test-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependecies
        run: npm ci
      - name: Run tests
        run: npm test

  test-windows:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependecies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    needs: [test-linux, test-windows]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react
    steps:
      - name: Pull code from git
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
